core/urls.py
from django.contrib import admin
from django.urls import path, include

# Your normal URLs here...
urlpatterns = [
    path('', include('tracks.urls')), # added
    path('admin/', admin.site.urls),
    # add for control authen account
    path('accounts/', include('django.contrib.auth.urls')),
]

tracks/urls.py
from django.urls import path
from . import views

app_name = 'tracks'

urlpatterns = [
    path('', views.TrackListView.as_view(), name='all'),
    path('tracks/<int:pk>/detail', views.TrackDetailView.as_view(), name='track_detail'),
    path('tracks/create/', views.TrackCreateView.as_view(), name='track_create'),
    path('tracks/<int:pk>/update/', views.TrackUpdateView.as_view(), name='track_update'),
    path('tracks/<int:pk>/delete/', views.TrackDeleteView.as_view(), name='track_delete'),
    path('ajax/load-failure-code/', views.load_failure_code,name='ajax_load_failure_code'),
    path('ajax/load-action-code/', views.load_action_code,name='ajax_load_action_code'),
    path('ajax/load-cause-code/', views.load_cause_code,name='ajax_load_cause_code'),
]

tracks/models.py
import datetime
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.translation import gettext as _
# Create your models here.


class EquipmentName(models.Model):
    equipmentName = models.CharField(_('Equipment Name'), max_length=125, null=True)

    def __str__(self):
        return self.equipmentName
    
    
class FailureCode(models.Model):
    
    equipmentName       = models.ForeignKey(EquipmentName, on_delete=models.CASCADE)
    failureShortName    = models.CharField(_('Failure Short Name'), max_length=125, null=True)
    failureCode         = models.CharField(_('Failure Code'), max_length=125, null=True)

    def __str__(self):
        return self.failureCode
    
class ActionCode(models.Model):
    
    equipmentName       = models.ForeignKey(EquipmentName, on_delete=models.CASCADE)
    actionShortName     = models.CharField(_('Action Short Name'), max_length=125, null=True)
    actionCode          = models.CharField(_('Action Code'), max_length=125, null=True)

    def __str__(self):
        return self.actionCode


class CauseCode(models.Model):
    
    equipmentName       = models.ForeignKey(EquipmentName, on_delete=models.CASCADE)
    causeShortName      = models.CharField(_('Cause Short Name'), max_length=125, null=True)
    causeCode           = models.CharField(_('Cause Code'), max_length=125, null=True)

    def __str__(self):
        return self.causeCode

    
class Track(models.Model):
    workOrder = models.CharField(_('Work Order'), max_length=125, null=True)
    equipmentName = models.ForeignKey(EquipmentName, on_delete=models.SET_NULL, null=True)
    serialNumber  = models.CharField(_('Serial Number'), max_length=125, null=True)
    failureCode   = models.ForeignKey(FailureCode, on_delete=models.SET_NULL, null=True)
    actionCode    = models.ForeignKey(ActionCode, on_delete=models.SET_NULL, null=True)
    causeCode     = models.ForeignKey(CauseCode, on_delete=models.SET_NULL, null=True)
    workDate = models.DateField(_('Work Date'), blank=True, null=True)
    compleateDate = models.DateField(_('Compleate Date'), blank=True, null=True)
    remark        = models.CharField(_('Remark'), max_length=125, null=True, blank=True)
    
    def __str__(self):
        return self.workOrder

    def get_fields(self):
        return [(field.verbose_name, field.value_from_object(self))
                if field.verbose_name != 'genre'
                else(field.verbose_name, Genre.objects.get(k=field.value_from_object(self)).equipmentName)
                for field in self.__class__._meta.fields[1:]]

tracks/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import Track, EquipmentName, FailureCode, ActionCode, CauseCode
from bootstrap_datepicker_plus.widgets import DatePickerInput

class TrackForm(forms.ModelForm):
    class Meta:
        model = Track
        fields = ['workOrder', 'equipmentName',
                'serialNumber', 'failureCode', 'actionCode', 'causeCode', 'compleateDate', 'remark']
          
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.fields["failureCode"].queryset     = FailureCode.objects.none()
        self.fields["actionCode"].queryset      = ActionCode.objects.none()
        self.fields["causeCode"].queryset       = CauseCode.objects.none()

        # Dropdown list for Failure Code , Action Code , Cause Code
        if 'equipmentName' in self.data:
            try:
                equipmentName_id = int(self.data.get('equipmentName'))
                self.fields['failureCode'].queryset = FailureCode.objects.filter(equipmentName_id=equipmentName_id).order_by('failureCode')
                self.fields['actionCode'].queryset  = ActionCode.objects.filter(equipmentName_id=equipmentName_id).order_by('actionCode')
                self.fields['causeCode'].queryset   = CauseCode.objects.filter(equipmentName_id=equipmentName_id).order_by('causeCode')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty FailureCode queryset
        elif self.instance.pk:
            self.fields['failureCode'].queryset     = self.instance.EquipmentName.FailureCode.order_by('failureCode')
            self.fields['actionCode'].queryset      = self.instance.EquipmentName.ActionCode.order_by('actionCode')
            self.fields['causeCode'].queryset       = self.instance.EquipmentName.CauseCode.order_by('causeCode')
            
   

tracks/views.py
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Track, FailureCode, ActionCode, CauseCode
from bootstrap_datepicker_plus.widgets import DatePickerInput
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import datetime
from .forms import TrackForm
from django.shortcuts import render

class TrackBaseView(View):
    model = Track
    # fields = ['workOrder', 'equipmentName',
    #           'serialNumber', 'failureCode', 'actionCode', 'causeCode', 'workDate', 'compleateDate', 'remark']
    fields = '__all__'
    success_url = reverse_lazy('tracks:all')
    
    
class TrackListView(TrackBaseView, ListView):
    """View to list all Tracks.
    Use the 'track_list' variable in the template
    to access all Track objects"""
    queryset = Track.objects.order_by('compleateDate')


class TrackDetailView(TrackBaseView, DetailView):
    """View to list the details from one Tracks.
    Use the 'track' variable in the template to access
    the specific Track here and in the Views below"""


    
class TrackCreateView(LoginRequiredMixin, TrackBaseView, CreateView):
    """View to create a new track"""  
    
    def get_form(self):
        '''add date picker in forms'''
        form = super(TrackCreateView, self).get_form()
        form.fields['compleateDate'].widget = DatePickerInput(options={"format": "DD-MM-YYYY"})
        form.fields['workDate'].widget = DatePickerInput(options={"format": "DD-MM-YYYY"})
        return form

      
class TrackUpdateView(LoginRequiredMixin, TrackBaseView, UpdateView):
    """View to update a track"""
    
    def get_form(self):
        '''add date picker in forms'''
        form = super(TrackUpdateView, self).get_form()
        form.fields['compleateDate'].widget = DatePickerInput(options={"format": "DD-MM-YYYY"})
        form.fields['workDate'].widget = DatePickerInput(options={"format": "DD-MM-YYYY"})
        return form


class TrackDeleteView(LoginRequiredMixin, TrackBaseView, DeleteView):
    """View to delete a Track"""


def load_failure_code(request):
    equipmentName_id = request.GET.get('equipmentName')
    failureCodes = FailureCode.objects.filter(equipmentName_id=equipmentName_id).order_by('failureCode')
    return render(request, 'tracks/failure_code_list_options.html', {'failureCodes': failureCodes})


def load_action_code(request):
    equipmentName_id = request.GET.get('equipmentName')
    actionCodes = ActionCode.objects.filter(equipmentName_id=equipmentName_id).order_by('actionCode')
    return render(request, 'tracks/action_code_list_options.html', {'actionCodes': actionCodes})

def load_cause_code(request):
    equipmentName_id = request.GET.get('equipmentName')
    causeCodes = CauseCode.objects.filter(equipmentName_id=equipmentName_id).order_by('causeCode')
    return render(request, 'tracks/cause_code_list_options.html', {'causeCodes': causeCodes})

templates/base.html
<!DOCTYPE HTML>
<html lang="en">

<head>

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.js" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js" rel="stylesheet">

{% block title %}
    {% if title %}
        <title>{{title}} | My Tracks</title> 
    {% else %}
        <title>My Data Table</title>
    {% endif %}
{% endblock title %}

{% block head %}
{% endblock head %}
    
</head>

<body>

<div class="container-fluid">
    
    <!-- NAVIGATION BAR -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="d-flex justify-content-between px-5 mx-auto" style="width: 80%;">
            <span class="navbar-text text-white">Track Spare parts</span>
            <ul class="navbar-nav mr-auto">

                
                <!-- 
                ##
                ## UNCOMMENT THESE LINES IF YOU HAVE A FUNCTIONAL CRUD FOR THE GENRE MODEL 
                ## CHANGE ALSO THE URL INFO 'films:all' to 'films:genre_all'     
                
                -->

                {% if user.is_authenticated %}
                
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'logout' %}?next={{next}}">Logout</a>
                </li>
                
                {% else %}
                
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'login' %}?next={{next}}">Login</a>
                </li>
                
                {% endif %}

            </ul>
        </div>
    </nav>

    <!-- END OF NAVIGATION BAR -->

</div>

{% block content %}
{% endblock content %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>


</body>

</html>

tracks/templates/tracks/action_code_list_options.html
<option value="">---------</option>
{% for item in actionCodes %}
<option value="{{ item.pk }}">{{ item.actionCode }}</option>
{% endfor %}

tracks/templates/tracks/cause_code_list_options.html
<option value="">---------</option>
{% for item in causeCodes %}
<option value="{{ item.pk }}">{{ item.causeCode }}</option>
{% endfor %}

tracks/templates/tracks/failure_code_list_options.html
<option value="">---------</option>
{% for item in failureCodes %}
<option value="{{ item.pk }}">{{ item.failureCode }}</option>
{% endfor %}

tracks/templates/tracks/track_confirm_delete.html
{% extends "base.html" %}

{% block content %}

{% url 'tracks:all' as list_all %}

<div class="container d-flex justify-content-center mt-5" style="width: 50%;">
    <div class="col mt-5 text-center">
        <h1 class="mb-5">Delete Track Work Order</h1>

        <p class="h5">Are you sure you want to delete the Track:Workorder</p>
        <h3 class="my-5">{{ track.workOrder }}</h3>
        <form action="" method="POST">
            {% csrf_token %}
            {% comment %} <input type="submit" value="Confirm">
            <input type="submit" value="Cancel" onclick="window.location='{% list_all %}'; return false;"> {% endcomment %}
            <input type="submit" class="btn btn-primary btn-lg" value="Confirm" style="margin-right: 30px; margin-top: 30px;">
            <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{{list_all}}'; return false;" value="Cancel">
        </form>
    </div>
</div>

{% endblock %}

tracks/templates/tracks/track_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">Track Details</h1>
        <div class="d-flex justify-content-center">
            <table class="table table-striped mt-5" style="width: 50%">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for label, value in track.get_fields %}
                    <tr>
                        <td>{{label | upper}}</td>
                        {%if label == 'Compleate Date' %}
                            <td>{{value | date:'d-m-Y'}}</td>
                        {%elif label == 'Work Date' %}
                            <td>{{value | date:'d-m-Y'}}</td>
                        {%elif label == 'Remark'%}
                            {% if value == None %}
                                <td></td>
                            {% else %}
                                <td>{{value}}</td>
                            {% endif %}
                        {%else%}
                            <td>{{value}}</td>
                        {%endif%}
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>

        <div class="d-flex justify-content-center">
            <a href="{% url 'tracks:all' %}" class="d-block btn btn-primary btn-lg my-5">BACK</a>
        </div>
    </div>

</div>

{% endblock %}

tracks/templates/tracks/track_form.html
{% extends "base.html" %}

{% block content %}

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}

{% url 'tracks:all' as list_all %}

{% url 'tracks:ajax_load_failure_code' as list_failure_code %}
{% url 'tracks:ajax_load_action_code' as list_action_code %}
{% url 'tracks:ajax_load_cause_code' as list_cause_code %}

{% load crispy_forms_tags %}

<!-- BOOTSTRAP FORM -->
<div class="container d-flex justify-content-center mt-5" style="width: 60%;">
    <div class="col mt-5">
        <form action="" method="post" id="tracksForm" 
            data-failure-code-url='{{list_failure_code}}' novalidate
            data-action-code-url='{{list_action_code}}' novalidate 
            data-cause-code-url='{{list_cause_code}}' novalidate>
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-6">
                    {{ form.workOrder|as_crispy_field }}
                </div>
                <div class="form-group col-6">
                    {{ form.equipmentName|as_crispy_field }}
                </div>
                <div class="form-group col-6">
                    {{ form.serialNumber|as_crispy_field }}
                </div>
                <div class="form-group col-6">
                    {{ form.failureCode|as_crispy_field }}
                </div>
                <div class="form-group col-6">
                    {{ form.actionCode|as_crispy_field }}
                </div>
                <div class="form-group col-6">
                    {{ form.causeCode|as_crispy_field }}
                </div>
                <div class="form-group col-6">
                    {{ form.workDate|as_crispy_field }}
                </div>
                <div class="form-group col-6">
                    {{ form.compleateDate|as_crispy_field }}
                </div>
                <div class="form-group col-6">
                    {{ form.remark|as_crispy_field }}
                </div>
            </div>
            <div class="container d-flex justify-content-center" style="width: 10%;">
                <input type="submit" class="btn btn-primary btn-lg" value="Submit"
                    style="margin-right: 30px; margin-top: 30px;">
                <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;"
                    onclick="window.location='{{list_all}}'; return false;" value="Cancel">
            </div>
        </form>
    </div>
</div>



<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_equipmentName").change(function () {

        var url1 = $("#tracksForm").attr("data-failure-code-url");
        var url2 = $("#tracksForm").attr("data-action-code-url");
        var url3 = $("#tracksForm").attr("data-cause-code-url");

        var equipmentNameId = $(this).val();                        // get the selected equipment Name ID from the HTML input

        $.ajax({                                        // initialize an AJAX request
            url: url1,                                  // set the url of the request 
            data: {
                'equipmentName': equipmentNameId        // add the country id to the GET parameters
            },
            success: function (data) {                  // `data` is the return of the `load_failure_code` view function
                
                $("#id_failureCode").html(data);        // replace the contents of the city input with the data that came from the server
            }
        });
        

        $.ajax({                                        // initialize an AJAX request
            url: url2,                                  // set the url of the request 
            data: {
                'equipmentName': equipmentNameId        // add the country id to the GET parameters
            },
            success: function (data) {                  // `data` is the return of the `load_failure_code` view function
                $("#id_actionCode").html(data);         // replace the contents of the city input with the data that came from the server
            }
        });

        $.ajax({                                        // initialize an AJAX request
            url: url3,                                  // set the url of the request 
            data: {
                'equipmentName': equipmentNameId        // add the country id to the GET parameters
            },
            success: function (data) {                  // `data` is the return of the `load_failure_code` view function
                $("#id_causeCode").html(data);          // replace the contents of the city input with the data that came from the server
            }
        });
    });
</script>

<!-- END BOOTSTRAP FORM -->

{% endblock %}

tracks/templates/tracks/track_list.html
{% extends 'base.html' %}

{% block content %}
<!-- Load from unpkg -->
<script src="https://unpkg.com/htmx.org@1.7.0"></script>

{% for track in track_list %}
{% for colname in track.column_set.all %}
<p>{{colname}}</p>
{% endfor %}
{% endfor %}

<div class="container d-flex mt-5" style="width: 70%;">
    <div class="col">
    <h1 class="text-center">SIS Track Spart Part</h1>
    <table class="table table table-striped mt-5">
        <thead>
            <tr>
                {% comment %} <th>#</th> {% endcomment %}
                <th class="text-center" scope="col">Work Order</th>
                <th class="text-center" scope="col">Equipment Name</th>
                <th class="text-center" scope="col">Serial Number</th>
                <th class="text-center" scope="col">Failure Code</th>
                <th class="text-center" scope="col">Action Code</th>
                <th class="text-center" scope="col">Cause Code</th>
                <th class="text-center" scope="col">Work Date</th>
                <th class="text-center" scope="col">Date Compleate</th>
                <th class="text-center" scope="col">Remark</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for track in track_list %}
            <tr>
                {% comment %} <th scope="row">{{forloop.counter}}</th> {% endcomment %}
                <td class="ml-5"><a href="{% url 'tracks:track_detail' track.id %}">{{track.workOrder}}</a></td>
                <td class="text-center">{{track.equipmentName}}</td>
                <td class="text-center">{{track.serialNumber}}</td>
                <td class="text-center">{{track.failureCode}}</td>
                <td class="text-center">{{track.actionCode}}</td>
                <td class="text-center">{{track.causeCode}}</td>
                <td class="text-center">{{ track.workDate | date:'d-m-Y' }}</td> 
                <td class="text-center">{{ track.compleateDate | date:'d-m-Y' }}</td> {% comment %} update format date "date:'d-m-Y'" {% endcomment %}
                {% if track.remark == None %}
                    <td class="text-center"></td>
                {% else %}
                    <td class="text-center">{{track.remark}}</td>
                {% endif %}
                <td><a href="{% url 'tracks:track_update' track.id %} ">Update</a></td>
                <td><a href="{% url 'tracks:track_delete' track.id %}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="d-flex justify-content-center">
        <a href="{% url 'tracks:track_create' %}" class="d-block btn btn-primary btn-lg my-5">Add New</a>
    </div>
    </div>
</div>
    


{% endblock content %}